### ISSUE TITLE
`mindev` segfaults when testing a rule type using a profile with alerts on

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#1858]
### Describe the issue

When running `mindev` we get the following error:

```
Profile valid according to the JSON schema!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x111d4aa]

goroutine 1 [running]:
github.com/stacklok/minder/internal/engine/actions.shouldAlert(0x0, {0x0?, 0x0?}, {0x19dc1a0, 0x243ce00?}, {0x149abd5, 0x4})
	github.com/stacklok/minder/internal/engine/actions/actions.go:171 +0x4a
github.com/stacklok/minder/internal/engine/actions.(*RuleActionsEngine).DoActions(0xc000571220, {0x19e9128, 0x24a3740}, {0x19dc060, 0xc00028a700}, {0x19ee0e8?, 0xc0003402d0?})
	github.com/stacklok/minder/internal/engine/actions/actions.go:119 +0x4de
github.com/stacklok/minder/internal/engine.(*RuleTypeEngine).Actions(...)
	github.com/stacklok/minder/internal/engine/rule_types.go:282
github.com/stacklok/minder/cmd/dev/app/rule_type.runEvaluationForRules(0xc000623500, 0xc000949c38, {0xc00013e4f0, 0x1, 0x0?})
	github.com/stacklok/minder/cmd/dev/app/rule_type/rttst.go:172 +0x225
github.com/stacklok/minder/cmd/dev/app/rule_type.testCmdRun(0xc00024eb00?, {0x1499a21?, 0x4?, 0x1499a25?})
	github.com/stacklok/minder/cmd/dev/app/rule_type/rttst.go:142 +0x72b
github.com/spf13/cobra.(*Command).execute(0xc0003d6300, {0xc0001117a0, 0x6, 0x6})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x2458800)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/stacklok/minder/cmd/dev/app.Execute()
	github.com/stacklok/minder/cmd/dev/app/root.go:43 +0x1a
main.main()
	github.com/stacklok/minder/cmd/dev/main.go:25 +0xf
```

### What version are you using?

`main`

**Comment by JAORMX** [comment]
@rdimitrov would be nice to get a dry run functionality that would show how the alert would have worked.
